source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!


target 'SwiftyVokoder', :exclusive => true do
  pod 'Vokoder/Swift', :path => '../'
  pod 'xUnique', :git => 'https://github.com/vokal/xUnique.git', :commit => '26adc7d50b'
end

target 'SwiftyVokoderTests', :exclusive => true do
  pod 'Vokoder/Swift', :path => '../'
end
