source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'SwiftyVokoder', :exclusive => true do
  pod "Vokoder", :path => "../"
end

target 'SwiftyVokoderTests', :exclusive => true do
  pod "Vokoder", :path => "../"
end
