source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'SwiftyVokoder' do
  pod 'Vokoder/Swift', :path => '../'
  pod 'xUnique', :git => 'https://github.com/vokal/xUnique.git', :commit => '43d39de'

  target 'SwiftyVokoderTests' do
  end
end
