//
//  Vokoder.h
//  Vokoder
//
//  Created by Carl Hill-Popper on 1/17/16.
//  Copyright © 2016 Vokal.
//

#ifndef Vokoder_h
#define Vokoder_h

//Xcode assumes a header file named the same as the module exists and includes it
//in the autogenerated swift interface to Obj-C classes.
//To allow for mixing Obj-C and Swift in the Vokoder framework,
//we create this empty file to satisfy the compiler.

#endif /* Vokoder_h */
