require 'fileutils'

default_platform :ios

platform :ios do

  #############
  # Variables #
  #############

  # Scheme/SDK combos to test
  schemes_to_test = [
    {
      workspace: "SwiftSampleProject.xcworkspace",
      scheme: "SwiftyVokoder",
      sdk: "iphonesimulator"
    },
  ]

  #########################
  # Pre-defined variables #
  #########################

  # The root fastlane folder (typically "fastlane")
  fastlane_folder = ENV['FASTLANE_FOLDER']

  # The output folder for building archives, relative to fastlane_folder
  # (typically "Build")
  build_folder = File.join(fastlane_folder, ENV['BUILD_FOLDER'])

  ###########
  ## SETUP ##
  ###########

  before_all do
    # Set up the shared environment keychain name. This is used by fastlane internals as
    # the keychain for signing certificates.
    ENV['KEYCHAIN_NAME'] = 'fastlane_keychain'
  end

  #############
  ## TESTING ##
  #############

  desc "Runs all the tests of the iOS App and gathers code coverage"
  lane :test do

    # Run tests for each scheme config
    schemes_to_test.each do |scheme_info|
      scan(
        workspace: scheme_info[:workspace],
        scheme: scheme_info[:scheme],
        sdk: scheme_info[:sdk],
        derived_data_path: build_folder,
        skip_build: true, #the test action will already kick off a build, don't build twice
      )
    end
  end

  
  ######################
  ## SUCCESS HANDLING ##
  ######################

  # This gets called if the executed lanes were all successful
  after_all do |lane|
    puts "Success!"
  end

  ######################
  ## FAILURE HANDLING ##
  ######################

  # This gets called if anything failed along the way
  error do |lane, exception|
    puts "FAIL!!!!: #{exception}"
  end
end
