source 'https://github.com/CocoaPods/Specs.git'

target 'MigrationProject' do
  pod 'Vokoder', :path => '../'
  pod 'xUnique', :git => 'https://github.com/vokal/xUnique.git', :commit => '43d39de'

  target 'MigrationProjectTests' do
    # No pods specific to this target, but it needs to be included
  end

end
