def vokoder_pod
  pod 'Vokoder', :path => '../'
end

target 'VOKCoreDataManager' do
  vokoder_pod
  pod 'xUnique', :git => 'https://github.com/vokal/xUnique.git', :commit => '26adc7d50b'

  target 'VOKCoreDataManager Tests' do
    inherit! :search_paths
  end

end

target 'TodayWidget' do
  vokoder_pod
end

target 'VOKCoreDataManager-OSX' do
  platform :osx, '10.9'
  vokoder_pod

  target 'VOKCoreDataManagerTests-OSX' do
    inherit! :search_paths
  end
end

target 'VOKCoreDataManager-tvOS' do
  platform :tvos, '9.0'
  vokoder_pod

  target 'VOKCoreDataManagerTests-tvOS' do
    inherit! :search_paths
  end
end

target 'WatchApp Extension' do
    platform :watchos, '3.0'
    vokoder_pod
end
