source 'https://github.com/CocoaPods/Specs.git'

def vokoder_pod
  pod 'Vokoder', :path => '../'
end

target 'VOKCoreDataManager' do
  vokoder_pod
  pod 'xUnique', :git => 'https://github.com/vokal/xUnique.git', :commit => '26adc7d50b'
end

target 'VOKCoreDataManager Tests' do
  vokoder_pod
end

target 'VOKCoreDataManager-tvOS' do
  platform :tvos, '9.0'
  vokoder_pod
  target 'VOKCoreDataManagerTests-tvOS' do
    #inherit Vokoder pod from parent
  end
end

target 'VOKCoreDataManager-OSX' do
  platform :osx, '10.9'
  vokoder_pod
  target 'VOKCoreDataManagerTests-OSX' do
    #inherit Vokoder pod from parent
  end
end

target 'TodayWidget' do
  platform :ios, '8.0'
  pod 'Vokoder/Extension', :path => '../'
end
